# View this document on https://editor.swagger.io.

openapi: 3.0.2

info:
  description: >
    A portal that streamlines the planning process for Oregon State University
    CS Applied students
  version: 1.0.0
  title: OSU CS Applied Plan Portal
  contact:
    email: 'thomasza@oregonstate.edu'
  license:
    name: MIT License
    url: 'https://github.com/osu-capstone-cs72/cs-applied-plan-portal/blob/master/LICENSE'

paths:
  /user:
    post:
      summary: Create a new User
      description: >
        TODO: Complete this section while implementing this API route
      operationId: createUser
      tags:
        - User

  /user/login:
    post:
      summary: Log a User in
      description: >
        TODO: Complete this section while implementing this API route
      operationId: login
      tags:
        - User

  /user/logout:
    post:
      summary: Log a User out
      description: >
        TODO: Complete this section while implementing this API route
      operationId: logout
      tags:
        - User

  '/user/{onid}':
    get:
      summary: Fetch data about a specific User
      description: >
        Returns information about a User with the provided `onid`.
      operationId: getUserByOnid
      tags:
        - User
      parameters:
        - name: onid
          in: path
          description: ONID of the User to fetch
          required: true
          schema:
            type: string
          example: doejohn
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User with the specified `userId` not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  '/user/{onid}/plan':
    get:
      summary: Fetch a list of applied Plan that belong to this User
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getPlansOfUser
      tags:
        - User

  '/course/{courseId}':
    get:
      summary: Fetch data about a specific Course
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getCourseById
      tags:
        - Course

  '/course/{courseCode}':
    get:
      summary: Fetch data about a specific Course based on course code
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getCourseByCode
      tags:
        - Course

  '/course/{courseName}':
    get:
      summary: Fetch data about a specific Course based on course name
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getCourseByName
      tags:
        - Course

  /plan:
    post:
      summary: Create a new applied Plan
      description: >
        TODO: Complete this section while implementing this API route
      operationId: createPlan
      tags:
        - Plan

    put:
      summary: Update an applied Plan
      description: >
        TODO: Complete this section while implementing this API route
      operationId: updatePlan
      tags:
        - Plan

    delete:
      summary: Remove an applied Plan
      description: >
        TODO: Complete this section while implementing this API route
      operationId: deletePlan
      tags:
        - Plan

  '/plan/{planId}':
    get:
      summary: Fetch data about a specific applied Plan
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getPlanById
      tags:
        - Plan

    patch:
      summary: Patch a specific Applied plan
      description: >
        TODO: Complete this section while implementing this API route
      opeartionId: patchPlanById
      tags:
        - Plan

  '/plan/{planId}/comments':
    get:
      summary: Fetch a list of comments linked to an applied Plan
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getCommentsOfPlan
      tags:
        - Plan

  /comment:
    post:
      summary: Create a new Comment
      description: >
        TODO: Complete this section while implementing this API route
      operationId: createComment
      tags:
        - Comment

  '/comment/{commentId}':
    get:
      summary: Fetch data about a specific Comment
      description: >
        TODO: Complete this section while implementing this API route
      operationId: getCommentById
      tags:
        - Comment

components:
  schemas:
    Comment:
      description: An object representing information about a comment
      type: object
      properties:
        commentId:
          description: The ID to uniquely identify the comment
          type: integer
          format: int64
          example: 72
        planId:
          description: The ID of the plan that the comment is attached to
          type: integer
          format: int64
          example: 72
        userId:
          description: The ID of the user who created the comment
          type: integer
          format: int64
          example: 72
        time:
          description: 'The time that the comment was created, in UTC'
          type: string
          format: date-time
          example: '2020-05-15T14:30:29Z'
        text:
          description: The text content of the comment
          type: string
          example: 'Your plan looks good!'

    Course:
      description: An object representing information about a course
      type: object
      properties:
        courseId:
          description: The ID to uniquely identify the course
          type: integer
          format: int64
          example: 72
        credits:
          description: The number of credits the course offers
          type: integer
          format: int32
          example: 4
        courseName:
          description: The name of the course
          type: string
          example: Cloud Application Development
        courseCode:
          description: The course code
          type: string
          example: CS493
        courseUrl:
          description: >
            The URL that corresponds with the OSU catalog listing of the course
          type: string
          example: 'https://example.com'
        restriction:
          description: >
            The restriction code of this course in the CS applied program
          type: integer
          format: int64
          example: 2

    Plan:
      description: An object representing information about an applied plan
      type: object
      properties:
        planId:
          description: The ID to uniquely identify the plan
          type: integer
          format: int64
          example: 72
        studentId:
          description: >
            The ID to uniquely identify the student that created the plan
          type: integer
          format: int64
          example: 72
        planName:
          description: 'The name of the plan, decided by the student'
          type: string
          example: My Artificial Intelligence Plan
        status:
          description: >
            An integer represents a specific status of a plan: 0 is `Rejected`,
            1 is `Awaiting Student Changes`, 2 is `Awaiting Review`, 3 is
            `Awaiting Final Review`, 4 is `Accepted`
          type: string
          example: 3
        lastUpdated:
          description: 'The time when the plan was last changed, in UTC'
          type: string
          format: date-time
          example: '2020-05-15T14:30:29Z'

    User:
      description: An object representing information about an application user
      type: object
      properties:
        userId:
          description: The ID to uniquely identify the user
          type: integer
          format: int64
          example: 72
        firstName:
          description: The first name of the user
          type: string
          example: John
        lastName:
          description: The last name of the user
          type: string
          example: Doe
        email:
          description: The OSU email of the user
          type: string
          format: email
          example: 'email@example.com'
        role:
          description: >
            The role of the user in the system: 0 is `Student`, 1 is `Advisor`,
            2 is `Head Advisor`
          type: integer
          format: int64
          example: 1

    Error:
      description: An object describing an error response from the system
      type: object
      properties:
        error:
          description: A message describing the error
          type: string
          example: Error message

  requestBodies:
    Comment:
      description: A Comment object
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comment'

    Course:
      description: A Course object
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Course'

    Plan:
      description: A Plan object
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Plan'

    User:
      description: A User object
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

tags:
  - name: User
    description: API endpoints related to application Users
  - name: Course
    description: API endpoints related to Courses
  - name: Plan
    description: API endpoints related to applied Plans
  - name: Comment
    description: API endpoints related to Comments
